version: "3"
x-minio-common: &minio-common
  image: minio/minio:RELEASE.2021-10-23T03-28-24Z
  command: server --console-address ":9001" http://minio{1...4}/data{1...2}
  expose:
    - "9000"
    - "9001"
  environment:
    MINIO_ROOT_USER: minioadmin
    MINIO_ROOT_PASSWORD: minioadmin
    MINIO_NOTIFY_WEBHOOK_ENABLE_AMPS: "on"
    MINIO_NOTIFY_WEBHOOK_ENDPOINT_AMPS: http://web:8090/events
    MINIO_NOTIFY_WEBHOOK_AUTH_TOKEN_AMPS: minioadmin
    MINIO_NOTIFY_WEBHOOK_QUEUE_DIR_AMPS: "/volumes/queue"
    MINIO_NOTIFY_WEBHOOK_QUEUE_LIMIT_AMPS: 1000000
    MINIO_NOTIFY_WEBHOOK_CLIENT_CERT_AMPS:
    MINIO_NOTIFY_WEBHOOK_CLIENT_KEY_AMPS:

  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3

services:
  web:
    image: amps_ufa:latest
    environment:
      # GENERATE A NEW SECRET KEY
      SECRET_KEY_BASE: "xhAYbJzLVVL6h+06ntgkFcV49mUz5ntU8E48vCQC4hL1ywiPAQpenEJIh9CWpStt"
      AMPS_ROOT_USER: "root"
      AMPS_ROOT_PASS: "test123"
      AMPS_AUTH_METHOD: "vault"
      AMPS_S3_SCHEME: "http://"
      AMPS_S3_HOST: nginx
      AMPS_S3_PORT: 9000
      AMPS_MINIO_ADDR: "http://nginx:9001"
      AMPS_MONGO_ADDR: "mongodb://mongo:27017/amf"
      AMPS_VAULT_ADDR: "http://vault:8200"
      MIX_ENV: prod
      TZ: "America/Chicago"
      PORT: 4000
    depends_on:
      - mongo
      - vault
      - nginx
    ports:
      - "4000:4000"
      # - "443:443"
    volumes:
      - ./volumes/keys:/app/keys
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - ./volumes/db:/data/db
  vault:
    image: vault
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/vault.json
    ports:
      - "8200:8200"
    volumes:
      - ./volumes/logs:/vault/logs
      - ./volumes/file:/vault/file
      - ./vault/config:/vault/config
  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - ./volumes/data1-1:/data1
      - ./volumes/data1-2:/data2

  minio2:
    <<: *minio-common
    hostname: minio2
    volumes:
      - ./volumes/data2-1:/data1
      - ./volumes/data2-2:/data2

  minio3:
    <<: *minio-common
    hostname: minio3
    volumes:
      - ./volumes/data3-1:/data1
      - ./volumes/data3-2:/data2

  minio4:
    <<: *minio-common
    hostname: minio4
    volumes:
      - ./volumes/data4-1:/data1
      - ./volumes/data4-2:/data2

  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4
