name: Docker Image CI

on:
  push:
    branches: [ standalone ]
  pull_request:
    branches: [ standalone ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    -  name: Build and push
       id: docker_build
       uses: docker/build-push-action@v4
       with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ vars.DOCKER_HUB_USERNAME }}/amps_backend:${{ github.sha }},${{ vars.DOCKER_HUB_USERNAME }}/amps_backend:latest
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
          
