name: Elixir CI

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run docker containers
      run: export curdir=$PWD && cd docker && docker-compose -f docker-compose.workflow.yml up -d && docker ps -a && cd $curdir
    - name: Test OpenSearch
      run: bash -c 'while [[ "$(curl -sk -u admin:admin -o /dev/null -w ''%{http_code}'' https://localhost:9200)" != "200" ]]; do sleep 5; done'
    - name: Test Vault
      uses: nev7n/wait_for_response@v1
      with:
        url: 'http://localhost:8200/v1/sys/health'
        responseCode: 501
        timeout: 30000
        interval: 500
    - name: Set up Elixir
      uses: erlef/setup-beam@988e02bfe678367a02564f65ca2e37726dc0268f
      with:
        elixir-version: '1.12.3' # Define the elixir version [required]
        otp-version: '24.1' # Define the OTP version [required]
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: mix deps.get
    - name: Run tests
      run: mix test
